plugins {
	id 'java'
	id 'org.springframework.boot' version '3.1.4'
	id 'io.spring.dependency-management' version '1.1.3'
}

group = 'com.jung'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = '17'
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
//	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
	useJUnitPlatform()
}

subprojects {
	apply plugin: 'java'
	apply plugin: 'org.springframework.boot'
	apply plugin: 'io.spring.dependency-management'

	repositories {
		mavenCentral()
	}

	dependencies {
		//	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
		implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
		implementation 'org.springframework.boot:spring-boot-starter-web'
		compileOnly 'org.projectlombok:lombok'
		annotationProcessor 'org.projectlombok:lombok'
		testImplementation 'org.springframework.boot:spring-boot-starter-test'
		implementation 'com.googlecode.json-simple:json-simple:1.1.1'

		implementation 'org.springframework.boot:spring-boot-starter-webflux:3.1.2'

	}

	test{
		useJUnitPlatform()
	}
}

project(':domain') {
	dependencies {
	}
}

project(':common') {
	dependencies {
	}
}

project(':client') {
	dependencies {
		implementation(project(":common"))
		implementation(project(":domain"))
		implementation 'org.springframework.boot:spring-boot-starter-webflux:3.3.3'
	}
}

project(':logic-api-module') {

	dependencies {
		implementation(project(":domain"))
		implementation(project(":common"))
		implementation(project(":client"))
		//엑셀 읽기 라이브러리
		implementation 'org.apache.poi:poi:5.2.3'
		implementation 'org.apache.poi:poi-ooxml:5.2.3'
		//DB JPA 라이브러리
		implementation 'org.springframework.boot:spring-boot-starter-data-jpa:3.2.0'
		//로컬 테스트용 h2 DB
		runtimeOnly 'com.h2database:h2'
		implementation 'mysql:mysql-connector-java:8.0.28'
	}
}

project(':message-module') {

	dependencies {
		implementation(project(":domain"))
		implementation(project(":common"))
	}
}

project(':admin') {

	dependencies {
		implementation(project(":domain"))
		implementation(project(":common"))

		//DB JPA 라이브러리
		implementation 'org.springframework.boot:spring-boot-starter-data-jpa:3.2.0'
		//로컬 테스트용 h2 DB
		runtimeOnly 'com.h2database:h2'
		implementation 'mysql:mysql-connector-java:8.0.28'

		implementation 'org.springframework.boot:spring-boot-starter-thymeleaf:3.1.5'
		implementation 'org.springframework.boot:spring-boot-devtools:3.1.5'


	}
}

project(':sell-admin') {

	dependencies {
		implementation(project(":domain"))
		implementation(project(":common"))
		implementation(project(":client"))

		//DB JPA 라이브러리
		implementation 'org.springframework.boot:spring-boot-starter-data-jpa:3.2.0'
		//로컬 테스트용 h2 DB
		runtimeOnly 'com.h2database:h2'
		implementation 'mysql:mysql-connector-java:8.0.28'

		implementation 'org.springframework.boot:spring-boot-starter-thymeleaf:3.1.5'
		implementation 'org.springframework.boot:spring-boot-devtools:3.1.5'


	}
}








